// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ReferralCardVariantA.tsx": () => import("../components/mockups/ReferralCardVariantA.tsx"),
  "./components/mockups/ReferralCardVariantB.tsx": () => import("../components/mockups/ReferralCardVariantB.tsx"),
  "./components/mockups/ReferralCardVariantC.tsx": () => import("../components/mockups/ReferralCardVariantC.tsx")
};
